### ISSUE TITLE
APDS-9930 proximity issue

### ISSUE THREAD

**Issue by kajaba** [Depau/APDS9930#8] opened 2017-06-05 19:42 UTC
Hello 
I found this implementation for APDS-9930, I have that module and used it with arduino, but your proximity example always 
shows
---------------------------
APDS-9930 - ProximitySensor
---------------------------
APDS-9930 initialization complete
Proximity sensor is now running
0: 0x5
1: 0xFF
2: 0xFF
3: 0xFF
4: 0xFF
5: 0xFF
6: 0x0
7: 0x0
8: 0x0
9: 0x0
A: 0x32
B: 0x0
C: 0x22
D: 0x0
E: 0x8
F: 0x2E
12: 0x39
13: 0x22
14: 0x0
15: 0x0
16: 0x0
17: 0x0
18: 0xE2
19: 0x1
1E: 0x0
Proximity: 462
Proximity: 480
Proximity: 415
Proximity: 459
Proximity: 455
Proximity: 425
Proximity: 406
Proximity: 406
Proximity: 380
Proximity: 409
Proximity: 422
Proximity: 485
Proximity: 447
Proximity: 427
Proximity: 430

values no matter what distance I use. It is Always around 400.

Ambient example look ok:
Ambient: 255.09  Ch0: 239  Ch1: 99
Ambient: 220.65  Ch0: 213  Ch1: 89
Ambient: 169.15  Ch0: 142  Ch1: 59
Ambient: 30.42  Ch0: 29  Ch1: 12
Ambient: 25.75  Ch0: 24  Ch1: 10
Ambient: 20.44  Ch0: 25  Ch1: 10
Ambient: 19.80  Ch0: 21  Ch1: 9
Ambient: 24.46  Ch0: 22  Ch1: 9
Ambient: 19.80  Ch0: 21  Ch1: 9
Ambient: 243.18  Ch0: 229  Ch1: 95
Ambient: 237.23  Ch0: 224  Ch1: 93
Ambient: 231.91  Ch0: 221  Ch1: 92

Do you think I have bad board? Thanks for your work in this field by the way

**Comment by depau** [comment] 2017-06-05 21:40
Duplicate of #7. No your board is not broken, it's crappy just as everybody else's.
Try messing with gain values, may help but no guarantees.

**Closed as completed by depau** 2017-06-05 21:40 UTC
Labels: duplicate, wontfix
